import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { supabase } from '../../lib/supabase';
import { getPracticeStats, PracticeStats } from '../../lib/progressStore';
import { useTheme } from '../../lib/theme';

export default function HomeScreen() {
  const { theme } = useTheme();
  const [stats, setStats] = useState<PracticeStats>(getPracticeStats()); const [vocabCount, setVocabCount] = useState(0);
  useEffect(()=>{const load=async()=>{const {count}=await supabase.from('vocabulary').select('id',{count:'exact',head:true});setVocabCount(count||0)};load();const id=setInterval(()=>setStats(getPracticeStats()),1000);return()=>clearInterval(id)},[]);
  const accuracy=stats.questions?Math.round(stats.correct/stats.questions*100):0;
  const Card=({children,style}:{children:React.ReactNode;style?:object})=><View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.line},style]}>{children}</View>;
  return <ScrollView style={{flex:1,backgroundColor:theme.bg}} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.eyebrow,{color:theme.primary}]}>LINGUA.</Text><Text style={[styles.title,{color:theme.ink}]}>Learn With confidence</Text><Text style={[styles.subtitle,{color:theme.muted}]}>Words, practice, speaking and progress in one place.</Text></View><View style={[styles.avatar,{backgroundColor:theme.primary}]}><Text style={styles.avatarText}>L</Text></View></View>
    <View style={styles.statsGrid}>{[[String(stats.sessions),'Practice sessions','Live'],[String(stats.correct),'Correct answers',`${accuracy}% accuracy`],[vocabCount.toLocaleString(),'Vocabulary records','Live library'],[String(stats.questions),'Questions answered',stats.lastSessionAt?'Recently active':'Start practicing']].map(([value,label,delta])=><Card key={label} style={styles.stat}><Text style={[styles.statLabel,{color:theme.muted}]}>{label}</Text><Text style={[styles.statValue,{color:theme.ink}]}>{value}</Text><Text style={[styles.delta,{color:theme.primary}]}>{delta}</Text></Card>)}</View>
    <Pressable style={[styles.hero,{backgroundColor:theme.primary}]} onPress={()=>router.push('/speak')}><Text style={styles.heroEyebrow}>SPEAKING COACH</Text><Text style={styles.heroTitle}>Practice real conversations without pressure.</Text><Text style={styles.heroText}>Choose a scenario, speak or type, and get immediate coaching.</Text><View style={styles.heroButton}><Text style={[styles.heroButtonText,{color:theme.primary}]}>Start speaking →</Text></View></Pressable>
    <Card><Text style={[styles.sectionTitle,{color:theme.ink}]}>Quick actions</Text><View style={styles.actions}>{[['Practice','20-question session','/practice'],['Bulk import','CSV vocabulary','/import'],['Browse words',`${vocabCount.toLocaleString()} records`,'/vocabulary'],['Flashcards','Recall & review','/flashcards']].map(([a,b,path])=><Pressable key={a} style={[styles.action,{backgroundColor:theme.surfaceAlt}]} onPress={()=>router.push(path as never)}><Text style={[styles.actionTitle,{color:theme.ink}]}>{a}</Text><Text style={[styles.meta,{color:theme.muted}]}>{b}</Text></Pressable>)}</View></Card>
    <Card><Text style={[styles.sectionTitle,{color:theme.ink}]}>Today's path</Text>{[['1','Learn new words','Open Vocabulary','/vocabulary'],['2','Practice recall','Open Practice','/practice'],['3','Review flashcards','Open Flashcards','/flashcards'],['4','Speak naturally','Open Speaking','/speak']].map(([n,title,meta,path])=><Pressable key={n} style={styles.lesson} onPress={()=>router.push(path as never)}><View style={[styles.lessonCircle,{backgroundColor:theme.soft}]}><Text style={[styles.lessonNumber,{color:theme.primary}]}>{n}</Text></View><View><Text style={[styles.lessonTitle,{color:theme.ink}]}>{title}</Text><Text style={[styles.meta,{color:theme.muted}]}>{meta}</Text></View><Text style={[styles.chevron,{color:theme.muted}]}>›</Text></Pressable>)}</Card>
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:20,paddingTop:24,paddingBottom:36,gap:16},header:{flexDirection:'row',justifyContent:'space-between',gap:12,alignItems:'flex-start'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1},title:{fontSize:30,lineHeight:35,fontWeight:'900',letterSpacing:-.7,marginTop:5,maxWidth:560},subtitle:{fontSize:14,lineHeight:20,marginTop:7,maxWidth:600},avatar:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900'},statsGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{flexGrow:1,flexBasis:'47%',minWidth:150},card:{borderRadius:20,borderWidth:1,padding:18},statLabel:{fontSize:12},statValue:{fontSize:27,fontWeight:'900',marginTop:6},delta:{fontSize:12,fontWeight:'700',marginTop:3},hero:{borderRadius:22,padding:22},heroEyebrow:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:1},heroTitle:{color:'#fff',fontSize:25,lineHeight:30,fontWeight:'900',marginTop:7,maxWidth:520},heroText:{color:'#fff',fontSize:14,lineHeight:20,marginTop:8,maxWidth:560,opacity:.85},heroButton:{alignSelf:'flex-start',backgroundColor:'#fff',borderRadius:12,paddingHorizontal:15,paddingVertical:11,marginTop:14},heroButtonText:{fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900',marginBottom:10},actions:{flexDirection:'row',gap:10,flexWrap:'wrap'},action:{flex:1,minWidth:145,borderRadius:14,padding:14},actionTitle:{fontWeight:'900'},meta:{fontSize:12,marginTop:3},lesson:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:9},lessonCircle:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'},lessonNumber:{fontWeight:'900'},chevron:{marginLeft:'auto',fontSize:24}});
