import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { supabase } from '../../lib/supabase';
import { getPracticeStats, PracticeStats } from '../../lib/progressStore';

const colors = { bg:'#F6F7FB', ink:'#172033', muted:'#667085', primary:'#5B5CE2', soft:'#EEEFFF', white:'#FFFFFF', line:'#E7E9F0', green:'#16A66A' };
function Card({ children, style }: { children: React.ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }

export default function HomeScreen() {
  const [stats, setStats] = useState<PracticeStats>(getPracticeStats());
  const [vocabCount, setVocabCount] = useState(0);
  useEffect(() => { const load=async()=>{ const {count}=await supabase.from('vocabulary').select('id',{count:'exact',head:true}); setVocabCount(count||0); }; load(); const id=setInterval(()=>setStats(getPracticeStats()),1000); return()=>clearInterval(id); },[]);
  const accuracy=stats.questions?Math.round(stats.correct/stats.questions*100):0;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>LINGUA.</Text><Text style={styles.title}>Build your English, one day at a time.</Text><Text style={styles.subtitle}>Words, practice, speaking and progress in one place.</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>L</Text></View></View>
    <View style={styles.statsGrid}>
      {[ [String(stats.sessions),'Practice sessions', 'Live'], [String(stats.correct),'Correct answers', `${accuracy}% accuracy`], [vocabCount.toLocaleString(),'Vocabulary records','Live library'], [String(stats.questions),'Questions answered', stats.lastSessionAt?'Recently active':'Start practicing'] ].map(([value,label,delta])=><Card key={label} style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text><Text style={styles.delta}>{delta}</Text></Card>)}
    </View>
    <Pressable style={styles.hero} onPress={()=>router.push('/speak')}><Text style={styles.heroEyebrow}>SPEAKING COACH</Text><Text style={styles.heroTitle}>Practice real conversations without pressure.</Text><Text style={styles.heroText}>Choose a scenario, speak or type, and get immediate coaching.</Text><View style={styles.heroButton}><Text style={styles.heroButtonText}>Start speaking →</Text></View></Pressable>
    <Card><View style={styles.sectionRow}><Text style={styles.sectionTitle}>Quick actions</Text></View><View style={styles.actions}><Pressable style={styles.action} onPress={()=>router.push('/practice')}><Text style={styles.actionTitle}>Practice</Text><Text style={styles.meta}>20-question session</Text></Pressable><Pressable style={styles.action} onPress={()=>router.push('/import')}><Text style={styles.actionTitle}>Bulk import</Text><Text style={styles.meta}>CSV vocabulary</Text></Pressable><Pressable style={styles.action} onPress={()=>router.push('/vocabulary')}><Text style={styles.actionTitle}>Browse words</Text><Text style={styles.meta}>{vocabCount.toLocaleString()} records</Text></Pressable></View></Card>
    <Card><View style={styles.sectionRow}><Text style={styles.sectionTitle}>Today's path</Text></View>{[['1','Learn new words','Open Vocabulary'],['2','Practice recall','Open Practice'],['3','Speak naturally','Open Speaking']].map(([n,title,meta],i)=><Pressable key={n} style={styles.lesson} onPress={()=>router.push(i===0?'/vocabulary':i===1?'/practice':'/speak')}><View style={styles.lessonCircle}><Text style={styles.lessonNumber}>{n}</Text></View><View><Text style={styles.lessonTitle}>{title}</Text><Text style={styles.meta}>{meta}</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}</Card>
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{padding:20,paddingTop:24,paddingBottom:36,gap:16},header:{flexDirection:'row',justifyContent:'space-between',gap:12,alignItems:'flex-start'},eyebrow:{color:colors.primary,fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.ink,fontSize:30,lineHeight:35,fontWeight:'900',letterSpacing:-.7,marginTop:5,maxWidth:560},subtitle:{color:colors.muted,fontSize:14,lineHeight:20,marginTop:7,maxWidth:600},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.white,fontWeight:'900'},statsGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{flexGrow:1,flexBasis:'47%',minWidth:150},card:{backgroundColor:colors.white,borderRadius:20,borderWidth:1,borderColor:colors.line,padding:18},statLabel:{color:colors.muted,fontSize:12},statValue:{color:colors.ink,fontSize:27,fontWeight:'900',marginTop:6},delta:{color:colors.green,fontSize:12,fontWeight:'700',marginTop:3},hero:{backgroundColor:'#292C63',borderRadius:22,padding:22},heroEyebrow:{color:'#BFC2FF',fontSize:11,fontWeight:'900',letterSpacing:1},heroTitle:{color:colors.white,fontSize:25,lineHeight:30,fontWeight:'900',marginTop:7,maxWidth:520},heroText:{color:'#D8D9F4',fontSize:14,lineHeight:20,marginTop:8,maxWidth:560},heroButton:{alignSelf:'flex-start',backgroundColor:colors.white,borderRadius:12,paddingHorizontal:15,paddingVertical:11,marginTop:14},heroButtonText:{color:'#292C63',fontWeight:'900'},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},sectionTitle:{color:colors.ink,fontSize:18,fontWeight:'900'},actions:{flexDirection:'row',gap:10,flexWrap:'wrap'},action:{flex:1,minWidth:150,backgroundColor:'#F8F8FC',borderRadius:14,padding:14},actionTitle:{color:colors.ink,fontWeight:'900'},meta:{color:colors.muted,fontSize:12,marginTop:3},lesson:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:9},lessonCircle:{width:40,height:40,borderRadius:20,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'},lessonNumber:{color:colors.primary,fontWeight:'900'},lessonTitle:{color:colors.ink,fontSize:15,fontWeight:'800'},chevron:{marginLeft:'auto',color:'#98A2B3',fontSize:24}});
